name: "PruebaSecrets"
on:
  workflow_dispatch:
jobs:
  terraform_apply:
    name: "PruebaSecrets"
    runs-on: ubuntu-latest
    steps:
      uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'MY_SECRET_NAME'
          value: 'Lorem ipsun dolor simit'
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
