name: Terraform Apply
on:
  workflow_dispatch:

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3


    - name: Verify Terraform version
      run: terraform --version

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validation
      run: terraform validate

    - name: Terraform Apply
      run: terraform apply -auto-approve
